### ISSUE TITLE
Reconstruction video is glitchy

### ISSUE THREAD

**Issue by maximecb** [Kaixhin/PlaNet#12]
I'm training on a custom robot arm environment and training seems to proceed and succeed, however, the reconstructed video has a lot of colorful noise.

What's confusing is that:
1. This noise is only on the side of the reconstructed images. The ground truth side of the video looks fine.
2. The png images saved from the last video frames look blurry (which is normal), but they don't look noisy.

I expected the reconstructed imae side of the video to look blurry, but not to have lots of random colorful noise pixels. There really seems to be something wrong with the encoding because this persists even after training overnight. Have you seen this before? Do you have some idea what the problem might be?

I uploaded example video and image files here: https://gofile.io/?c=TLvvgH. I'm running this inside of a Ubuntu/PyTorch docker image.

**Comment by Kaixhin** [comment]
I know the video encoding is a bit lossy, but this is definitely strange (thanks for sharing video and image files). My only suspicion at the moment is that the values being produced by the network are actually beyond the [0, 1] range, which is being handled OK by the image creation, but not the video creation. If so then practically you could just clamp the values (though if this is the case it's actually a possibly useful diagnostic).

If not then guess you might need to check an alternative to opencv-python (which I am using already for fast downsampling of images, so was nice to not introduce another dependency).

**Comment by maximecb** [comment]
I checked and the values are in [0, 255] when they are about to be written out as video, so the problem must be happening somewhere before. I'm curious why this would be happening with my environment and not others. Are you on Linux or MacOS?

**Comment by Kaixhin** [comment]
I've managed to get fine videos after a bit of training on both DM Control's walker-walk and Gym's Pendulum on both Linux and Windows, but never tried MacOS (and I've not trained on other envs except for the other DM Control tasks).

**Comment by maximecb** [comment]
Just asking because I'm on Linux here.

I've confirmed that the pixel values in `write_video` are outside of the [0, 255] range:
```
frames min/max -43.072254 358.20514  
```

I will try to clip these. It could be useful to have an `observation_model` that has a tanh output layer and produces values in [-1, 1] instead of [-0.5, 0.5] to make it impossible for the model to predict out of range values.

**Comment by maximecb** [comment]
Okay that seems to fix the problem!

**Comment by Kaixhin** [comment]
Yep seems lucky that the original worked without needing to do this. I'd like to keep the implementation as close to the original as possible (and not add too many extra features to keep down maintenance), but happy to add an optional flag to add a tanh to the output model and/or just add a comment somewhere. What do you think?

**Comment by Kaixhin** [comment]
Just saw your PR, seems easier, thanks.
