### ISSUE TITLE
Altering Core Components

### ISSUE THREAD

**Issue by Ty4Code** [Kaixhin/PlaNet#2]
I'm looking to apply PlaNet to an actual control problem and I think this implementation may be a great starting point in that effort. I'm curious about potentially altering two pieces of the infrastructure, and am interested in hearing feedback on the difficulty of implementing the changes and also the potential implications on theory/performance. The two infrastructure components I am hoping to modify are:

1) Remove the encoder/decoder components.
The control problem I am dealing with already contains a compact latent representation of the state space (e.g. states are not images), which means that I don't think there would be much benefit in using the encoder/decoder transformations. By removing these components, I am assuming that learning is likely to be even faster since the latent representation is provided instead of having to be learned. Is that a fair assumption, and would it likely be easy to implement these changes?

2) Discretizing Action Space
The control problem I'm interested in is likely more easy to learn with a discrete action space rather than a continuous Gaussian action space. I imagine that this will likely be an easy modification to the Planner modual and will make learning easier due to a smaller action space, but is there potential theoretical considerations behind using a discrete action space for PlaNet?

Thanks for any discussion or feedback.

**Comment by Kaixhin** [comment]
Yep feel free to fork and adjust to your needs.

1. You could remove the encoder, but you will still need to train the decoder loss (this can be a small network though). Very easy to do.
2. You would need to replace CEM with a discrete planning algorithm, so doable (I'm planning to do this in the future based on some of my previous research, but may take me months to get around to it if at all), but far from trivial. In the original repo people are discussing using it for Atari, and they're discretising the continuous actions in [-1, 1] to the set of underlying discrete actions - this is the simplest way to deal with it for now.
