### ISSUE TITLE
how long does it take for each environment to train?

### ISSUE THREAD

**Issue by xinleipan** [Kaixhin/PlaNet#21]
I'm wondering besides the steps data, could you also provide the actual running time for some environments with visual input? Typically how long does it take for a model to converge on a single GPU?

**Comment by Kaixhin** [comment]
From what I remember, it takes about 1.5 weeks on a GTX 1080 Ti. Hopefully `tqdm` provides a reasonable estimate after some time. Unfortunately I have one GPU on a machine which I use for all of my work, so can't provide time estimates with a machine that isn't sometimes being used for other things.
