### ISSUE TITLE
Are RNN hidden states ever reset?

### ISSUE THREAD

**Issue by adamconkey** [Kaixhin/PlaNet#26]
It's common to reset RNN hidden states when, e.g. starting a new sequence, so that it doesn't hold on to potentially unrelated hidden states at the beginning of the sequence. As far as I can tell that never happens for the GRU in the RSSM model. Is this intentional, and if they were reset between chunks that are processed could this affect the performance? I haven't tried yet, but my feeling is if you don't reset it has to try to forget things at the beginning before it catches up with the memory necessary for the current sequence being processed.

Thanks for your help.

**Comment by Kaixhin** [comment]
During training it starts with a zeroed initial state for each sequence chunk (https://github.com/Kaixhin/PlaNet/blob/master/main.py#L167) and also at the beginning of data collection episodes (https://github.com/Kaixhin/PlaNet/blob/master/main.py#L220) and testing episodes (https://github.com/Kaixhin/PlaNet/blob/master/main.py#L252). Is there a place where you think it's being passed/not being passed incorrectly?

**Comment by adamconkey** [comment]
I see, okay I think that seems correct to me. I've only ever used RNNs in TF Keras, and there you have [functions and attributes on the RNN model](https://stackoverflow.com/questions/43882796/when-does-keras-reset-an-lstm-state) itself to manage the hidden state. Then when searching for resets for PyTorch I was seeing things like [this](https://discuss.pytorch.org/t/when-to-initialize-lstm-hidden-state/2323) and I was thinking there was then a similar model reset in PyTorch, but I see now those are just custom reset functions people wrote. I think it's simpler that you have to just pass in the hidden state as another input and manage it yourself like you did, it was always so confusing training in Keras.

Thanks!
