### ISSUE TITLE
Terminal State handling

### ISSUE THREAD

**Issue by mctigger** [Kaixhin/PlaNet#28]
Hi :)

How do you handle terminal states? I did not see any special handling the code. 
Since PlaNet does not predict termination, the only solution is to use absorbing states. However, for this we must train the model explicitly we absorbing states in mind, right?

**Comment by mctigger** [comment]
I looked in the model/algo files, but the absorbing states are implemented by not resetting the environment after done=True is received, but when a specific number of frames has passed.

**Comment by Kaixhin** [comment]
Correct - PlaNet doesn't predict termination. For the DeepMind Control environments tested on, that isn't so much of an issue. Some of the later work that builds on top of PlaNet does however take termination into account.
