### ISSUE TITLE
Potential error in the latent overshooting objective

### ISSUE THREAD

**Issue by jan1854** [Kaixhin/PlaNet#29]
Hi, I think there might be a small error in the implementation of the latent overshooting objective. In the following line the prior (`overshooting_vars[4]`) is passed as initial state to the transition model.
https://github.com/Kaixhin/PlaNet/blob/dacf418bd2760675e32ab90b1f1a149dee3eeaac/main.py#L187
If I understand the code correctly, this prior state corresponds to s<sub>t-d</sub> from equation (7) of the PlaNet paper. However, in the paper s<sub>t-d</sub> is sampled from the posterior distribution q(s<sub>t-d</sub> | o<sub>&le; t-d</sub>), not the prior.
The original implementation seems to use the posterior as initial state as well (see https://github.com/google-research/planet/blob/c04226b6db136f5269625378cd6a0aa875a92842/planet/tools/overshooting.py#L126-L134).

So I think the posterior rather than the prior should be used as initial state here.

**Comment by Kaixhin** [comment]
I think you're right, thanks for spotting. I won't be able to work on this now, so would you be able to send in a PR that fixes this?

**Comment by jan1854** [comment]
Yes, sure
